//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalkaTIPServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAPIs
    {
        public long CorrelationID { get; set; }
        public long CorrelatedUserID { get; set; }
        public string ApiUri { get; set; }
        public string ApiName { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
